Feature/oyc 14
Velociraptor33/OpenYourCityFront pull request #11
Opened 2021-08-09 18:58 UTC by Eldors

2021-08-10 15:03 UTC, iorlovsky requested changes

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.html
> +<button [ngClass]="[type]" class="button button__container button__text-style">
Будет прощее сделать так:
```
<button class="button button__container button__text-style button--{{type}}">
```
Тогда button--{{type}} будет преобразовываться в button--primary, button--secondary в зависимости от переданного type

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.html
> +<button [ngClass]="[type]" class="button button__container button__text-style">
И давай плиз переименуем поле type в severity. Type у кнопки выполняет отдельную [функцию](http://htmlbook.ru/html/button/type). Я забыл про это :с 
Логичнее будет использовать @Input() type для указания именно этого типа кнопки, а не визуального оформления

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> + .button__container {
container - это именно элемент блока button? Он не должен быть отдельным блоком?

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> + .button__container {
я не гуру бэма, могу заблуждаться)

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> + .button__text-style {
То же, что и про container

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> + .secondary {
primary, secondary и други классы должны быть модификаторами блока button. button--primary например.
Кстати scss позволяет делать такие штуки:
```
.button {
  // стили button

  &--primary {
    // стили button--primary

    &:hover {
      // стили button--primary:hover
    }
  }
}
```
https://sass-lang.com/documentation/style-rules/parent-selector

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +   background-color: #E3F2FD;
Давай в создадим файл src/styles/variables/_colors.scss.
В нем будем хранить константы с цветами, например
$color-primary-white: #fff;
$color-secondary-white: #fffffa;
$color-primary-success: #009933;
$color-primary-danger: #cc3300;

secondary/primary/danger и другие модификаторы относятся не только к цвету кнопок, но и ко всем элементам. Посмотри мокапы, там скорее всего у большинства элементов один и тот же набор цветов.

После создания _colors.scss, создай файл _variables.scss в каталоге variables и в нем импортируй _colors.scss:
@import "./colors";

Далее в файле angular.json в секцию styles https://github.com/Velociraptor33/OpenYourCityFront/blob/fb3b9592fb3d87d4e72f3efdb4b3f5f52efc4051/angular.json#L34
добавь путь к папке styles "src/styles" и variables: "src/styles/variables". Таким образом компилятор scss будет знать, что эти директории тоже нужно компилировать и из них можно делать импорты.

В итоге, работая, например, в button.component.scss ты сможешь использовать переменные, импортировав _variables.scss:

@import "variables";

.button {
  color: $color-primary-success;
}

2021-08-10 15:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  @Input() type!: string;
Давай не будем использовать `!`, я не уверен, что это хорошая практика, ибо этот оператор вроде как нужен для того, чтобы выключить проверки компилятора для типов null и undefined.

Еще мы можем указать более узкий тип данных для этого поля. Сейчас у тебя кнопка будет корректно работать, только если передать строки 'primary', 'secondary' и тд. Если я передам например 'lol', кнопка сломается. Мы можем использовать string literal union чтобы указать подмножество строк https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-types.
Тогда если я передам непредусмотренную строку, приложение просто не скомпилируется, что позволит избежать ошибки в рантайме

2021-08-10 18:03 UTC, Eldors commented on src/app/shared/components/button/button.component.scss
> + .button__container {
> container - это именно элемент блока button? Он не должен быть отдельным блоком?

в данном случае я контейнер использовал как врапер, но если его рассматривать как стиль кнопки ( в UIkit как раз обычные кнопки идут как contained ), то он должен быть блоком.

2021-08-14 13:03 UTC, iorlovsky commented on src/styles.scss
> +  font-family: 'Roboto', sans-serif;
Создай файлы src/styles/mixins/_fonts.scss и src/styles/mixins/_mixins.scss. В файле _mixins.scss сделай импорт ./fonts.scss, по аналогии с файлами переменных.
В _fonts.scss создай миксин
font-roboto, принимающий следующие аргументы:

1. size,
2. color,
3. weight.

Миксин должен устанавливать

- font-family: font-family: 'Roboto', sans-serif;
- размер текста, цвет текста и начертание. 

Аргументы миксина должны иметь дефолтные значения, чтобы его можно было использовать следующим образом:
```
.selector1 {
  @include font-roboto(14px, black, 500);
}
.selector2 {
  @include font-roboto(14px, black);
}
.selector3 {
  @include font-roboto(14px);
}
.selector4 {
  @include font-roboto();
}
```
Миксины импортируются так же, как и переменные.
Дока: https://sass-lang.com/documentation/at-rules/mixin

2021-08-14 22:01 UTC, iorlovsky commented on src/app/app.component.html
> +<oyc-button [severity]="'primary'" [shape]="'outlined'"></oyc-button>
Коммент по оформлению кода: если элемент содержит более одного атрибута, давай переносить их на новые строки, т.е. это должно выглядеть так:
```
<oyc-button
  [severity]="'primary'"
  [shape]="'outlined'">
</oyc-button>
```

2021-08-14 22:03 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> + @import "../../../../styles/variables/variables";
Можно использовать более короткий вариант
@import "variables"

Добавление stylePreprocessorOptions нужно как раз чтобы избежать таких длинных импортов

2021-08-14 22:05 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +   width: 94px;
Вместо width давай использовать min-width. Тогда минимальный размер кнопки будет 94пх, а максимальный неограничен

2021-08-14 22:06 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +   margin: 5px;
Зачем на margin? Так кнопка будет влиять на соседние элементы

2021-08-14 22:39 UTC, iorlovsky commented on src/styles.scss
> +  // font-family: 'Roboto', sans-serif;
довай удолим

2021-08-14 22:39 UTC, iorlovsky commented on src/styles/mixins/_font.scss
> +  line-height: 16px;
зачем line-height?

2021-08-14 22:47 UTC, iorlovsky commented on src/styles/mixins/_font.scss
> +@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap');
Этот импорт влияет на все приложение, а данный файл предназначен только для миксинов.
Давай создадим файл src/styles/resources/_fonts.scss. Туда перенесем этот импорт, затем импортируем resources/_fonts.scss в styles.scss

2021-08-14 22:51 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +       color: $color-danger-red-uotlined;
очепятка uotlined
мб посмотреть какой-то плагин вроде spell check, если опечатки не подсвечиваются

2021-08-16 17:13 UTC, iorlovsky approved these changes

2021-08-17 17:56 UTC, merged