[OYC-16] feat: Testing attribute directives
Velociraptor33/OpenYourCityFront pull request #16
Opened 2021-08-18 20:37 UTC by Eldors

Не понимаю почему компонентам не добавляется класс

2021-08-26 20:13 UTC, iorlovsky commented on src/app/app.component.html
> +  [disabled]="'isButtonDisabled'"
почему ты строку передаешь?) Поле disabled ведь boolean

2021-08-26 20:27 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +    if (this.element.classList.contains('button-disabled')) {
привязываться к классу - не оч круто. Если мы захотим переименовать класс, придется менять код в директиве. А про нее лего забыть.
Лучше сделать @Input rippleDisabled: boolean

2021-08-26 20:28 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +  @Input() color: 'red' | '' = ''; // '' = 'red';
это поле где-то используется? Ну и тип для него не слишком удобно подобран. Предполагается, что мы можем передать туда hex или rgb строку, поэтому тайп юнион не очень подходит для такой задачи. Просто string будет лучше

2021-08-26 20:31 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +  element: any;
any стоит использовать только в случае крайней необходимости, ибо any - это абсолютно любой тип. В данном случае тип поля element - HtmlElement

2021-08-26 20:36 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +    const circle = document.createElement('span');
Желательно не использовать методы DOM напрямую. Ангуляр имеет набор инструментов, позволяющий работать с документом через абстракции.
http://coldfox.ru/article/5ce1e246f7dc2f02ef7ef429/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D0%BC-Renderer2-%D0%B2-Angular
https://angular.io/api/core/Renderer2
Это удобно при тестировании и позволяет не привязывать приложение к браузерному окружению.
С помощью сервиса Renderer2 можно создавать элементы, добавлять классы и т.п. в общем выполнять любые манипуляции с документом

2021-08-26 20:37 UTC, iorlovsky commented on src/app/shared/components/button/button.component.html
> +<button class="button button--{{severity}} button-shape--{{shape}}" [class.button-disabled]="disabled" oycRipple>
должно быть button--disabled. disabled - это модификатор

2021-08-26 20:38 UTC, iorlovsky requested changes

2021-08-26 20:38 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +   height: 94px;
не слишком много для кнопки?)

2021-08-26 20:39 UTC, iorlovsky commented on src/app/shared/components/button/button.component.scss
> +   overflow: hidden;
зачем это свойство?

2021-08-26 20:40 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  @Input() disabled: 'isButtonDisabled' | '' = '';
boolean

2021-08-26 20:41 UTC, Eldors commented on src/app/shared/components/button/button.component.scss
> +   height: 94px;
Например в той же джире кнопки примерно такие же

2021-08-26 20:42 UTC, Eldors commented on src/app/shared/components/button/button.component.scss
> +   overflow: hidden;
для того, чтобы можно было применить рипл эффект внутри кнопки с абсолютным позиционированием и чтобы эффект был виден только внутри кнопки

2021-08-26 20:45 UTC, iorlovsky commented on src/styles.scss
> +// }
Давай будем стараться хранить этот файл максимально лаконичным. Все стили, которые должны быть доступны глобально, нужно хранить в соответствующих файлах и импортировать эти файлы здесь. Таким образом, в styles.scss не будет ничего кроме импортов. Тогда файл будет маленьким, а стили лучше структурированы.
Давай для рипл эффекта создадим файл src/styles/elements/_ripple.scss и опишим стили там

2021-08-26 20:49 UTC, iorlovsky commented on src/styles.scss
> +  // &:last-child {
В реквесте много закоментированных строк. Их нет смысла хранить. Удали весь закомменченный код одним коммитом с соответсвующим названием. Тогда, если удаленный код нужно будет вернуть, ты найдешь коммит в гите и откатишь его, чтобы вернуть стили. Или просто возьмешь нужные строки из этого коммита

2021-08-29 14:04 UTC, iorlovsky commented on angular.json
> +                "src/styles/elements"
Вот это не нужно добавлять в stylePreprocessorOptions, потому что elements не будет использоваться вне папки styles

2021-08-29 14:04 UTC, iorlovsky commented on src/app/app.component.html
> +<h1 oycRipple>Let's open your city!</h1>
Работает?)

2021-08-29 14:10 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  @Input() rippleColor: string = 'rgba(36, 34, 34, 0.7)';
Нам не нужно передавать rippleColor в кнопку извне. Кнопки будут везде одинаковые, и цвет риплов тоже.
Цвет риплов должен отличаться только в зависимости от severity и должен определяться на уровне кнопки, а не где-то вовне.
Предлагаю создать маппинг вида
severityToRippleColor = { 
  'primary': 'black',
  'secondary': 'red'
}
И в шаблоне использовать примерно так: [rippleColor]="severityToRippleColor[severity]".
Цвета взять из uikit

2021-08-29 14:16 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +}
кстати, этот файл должен быть в src/app/shared/directives а не в src/app

2021-08-29 14:17 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +  @Input() rippleColor!: string;
знак ! не нужно использовать. Сделай по умолчанию 'fff' цвет

2021-08-29 14:17 UTC, iorlovsky commented on src/app/ripple.directive.ts
> +    const circle = document.createElement('span');
👍

2021-08-29 14:20 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  @Input() disabled: true | false = false;
boolean...

2021-10-23 23:30 UTC, iorlovsky submitted a review, later dismissed

2021-10-23 23:40 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  severityToRippleColor: { [index: string]: any } = {
type ButtonSeverity = 'primary'
    | 'secondary'
    | 'warning'
    | 'danger'
    | 'success';

type ButtonShape: 'contained' | 'outlined';

severityToRippleColor: Record<ButtonShape, Record<ButtonSeverity, string>> = {...}

2021-10-23 23:43 UTC, iorlovsky requested changes
-

2021-10-30 15:17 UTC, iorlovsky commented on src/app/shared/components/button/button.component.ts
> +  @Input() severity:
для поля severity и shape можно использовать созданные типы.
Поправь это и гоу мержить

2021-10-30 15:18 UTC, iorlovsky approved these changes

2021-10-30 16:07 UTC, merged